server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb
      host: mongodb
      port: 27017
      database: mydb
      username: root
      password: root
      authentication-database: admin
jwt:
  secret: ${SECRET_KEY}
