spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    hibernate:

  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb
      host: mongodb
      port: 27017
      database: mydb
      username: root
      password: root
      authentication-database: admin
#      ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true
jwt:
  secret: ${SECRET_KEY}