spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    hibernate:
#      ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true
